const data =
    [
        {
            title: "JEDA DI TEKODEKO KOFFIEHUIS SEMARANG",
            content: "Kota Lama Semarang takkan pernah kehilangan pesonanya. Dan meski sudah beberapa kali ke sini, saya takkan pernah bosan mampir lagi. Indahnya peninggalan masa lalu nan klasik selalu mampu membuat jatuh hati.\nBEBERAPA waktu lalu saya diberi kesempatan lagi untuk mengunjungi Semarang, Jawa Tengah. Di sela-sela urusan pekerjaan saya mencuri waktu untuk mampir ke Kota Lama yang menjadi jantung dan detak indahnya kota ini. Kota Lama masih saja menawan. Tiap sudutnya terasa layak untuk diabadikan.\nSetelah puas berkeliling Kota Lama di sore yang cukup terik itu, dahaga pun datang. Saat itu saya berada tak jauh dari satu kedai kopi yang berdiri di bangunan tua. Ya, namanya Tekodeko Koffiehuis. Salah satu coffee shop di Kota Lama yang berdiri pada gedung tua yang anggun dan cantik. Tanpa berpikir lama saya pun singgah dan memilih berjeda bersama kopi di sana.\nTeko Deko Koffiehuis terdiri dari dua lantai. Di bagian lantai dua kamu bisa duduk di balkon sambil menonton manusia berlalu lalang di Kota Lama. Tapi karena cuaca agak terik jadi saya memilih duduk di lantai satu dekat jendela. Ada beberapa meja dan kursi yang terisi di sini meski tidak terlalu ramai. Di sini banyak menu minuman yang tak hanya kopi saja, namun tersedia juga minuman mocktail segar.\nOh iya, tak hanya menu espresso based, menu manual brew pun ada. Saya mau pesan yang simpel saja. Iced Americano saya pilih untuk redakan haus yang luar biasa. Iced Americano-nya lumayan. Rasanya cukup seimbang. Tidak pahit namun tetap ada body, dan low acidity. Cukuplah menjadi asupan kafein yang menyenangkan untuk saya lanjut bertualang keliling Kota Lama lagi.\nTekodeko Koffiehuis ini lokasinya strategis sekali. Tak jauh dari bar and bistro Spiegel yang terkenal itu. Terus yang membuat betah di sini adalah keindahan bangunan tuanya yang tetap terawat. Dinding-dinging yang dibiarkan cantik begitu saja, langit-langit yang khas bangunan tua serta lantai kedai kopinya pun tak luput dari keindahan.",
            imageUrl: "https://majalah.ottenstatic.com/uploads/2022/05/29A4DDEE-748A-450B-862C-CE16B355544F.jpg",
            author: "Mustika Treisna Yuliandri",
            tag: "Cafe & Travel,Indonesia,Java,Semarang",
            createdAt: "16-05-2022"
        },
        {
            title: "MENYERUPUT MALAM DI KOPI ANGKRINGAN KAKEK",
            content: "BULAN suci ramadan sedikit banyak menggeser waktu ngopi banyak orang. Tak terkecuali waktu ngopi saya. Yang biasanya pagi dan siang hari, kini bergeser menjadi di waktu berbuka. Saya tidak terbiasa ngopi di saat sahur. Karena rasanya kurang asyik saja. Maka waktu ngopi paling tepat adalah beberapa jam setelah berbuka.\n Dan beberapa saat lalu saat berjalan kaki mencari warung, saya dan seorang teman tak sengaja menemukan angkringan yang berjualan kopi. Saya pikir angkringan hanyalah milik warga Yogyakarta dan sekitarnya, tak menyangka di Medan pun ada. Angkringan ini berada di depan Tugu Juang Jalan Perintis Kemerdekaan dan H. M Yamin S.H Medan. Berjejer bersama pedagang kaki lima lainnya.\n Cukup menggoda rasanya untuk tidak disinggahi. Apalagi malam itu kami memang belum ngopi. Di tengah hiruk pikuk jalanan yang sibuk, Kopi Angkringan Kakek ini menjadi oase. Tak hanya kami, ada beberapa orang yang ikutan mampir setelah ibadah solat tarawih. Saya melihat ada beberapa alat seduh kopi. Mulai dari coffee dripper V60 hingga mesin kopi kecil otomatis. Ada pula beberapa biji kopi yang berjejer di toples-toples.\n Harga kopinya pun cukup terjangkau. Mulai dari 10 ribu rupiah saja. Saya awalnya ingin memesan filter coffee namun saya single origin mereka katanya sedang habis. Jadilah kami hanya memesan menu kopi hitam. Saat tiba kopi hitam ini menurut saya adalah lungo. Lungo sendiri adalah espresso yang dipanjangkan alias espresso dengan kuantitas sedikit lebih banyak dari biasa.\n Kenapa saya bisa menebak lungo karena minuman kami ini terlalu pekat dan sedikit untuk disebut Americano dan terlalu banyak untuk disebut doppio atau espresso. Meskipun tidak jelas menunya apa, kami tetap seru menikmati. Kopinya cukup bisa dinikmati meski rasanya biasa saja. Yang membuat seru ngopi di sini sebenarnya adalah suasananya. Kapan lagi menyeruput kopi malam-malam sembari menikmati hiruk pikuk Medan di malam ramadan?",
            imageUrl: "https://majalah.ottenstatic.com/uploads/2022/04/DD32C194-5C46-437E-9CC5-53AE7A61346F.jpg", 
            author: "Mustika Treisna Yuliandri",
            tag: "Cafe & Travel,Indonesia,Sumatra,Medan",
            createdAt: "10-04-2021"
        },
        {
            title: "BERJEDA DI COFFEE STOP CEBU FILIPINA",
            content: "CEBU City adalah kota penuh warna yang menarik hati. Sekilas memang sangat identik dengan Indonesia. Baik suasana, maupun rupa manusia. Namun, kota ini begitu kental sejarah dan nuansa Katolik. Gereja-gereja katedral dan bangunan khas Eropa menghiasi seluruh Cebu City.\nKami sendiri menjelajah beberapa tempat yang disarankan banyak situs di internet. Cukup melelahkan juga tapi menyenangkan luar biasa. Dan sore itu saat laju langkah melambat, maka yang kami butuhkan cuma jeda sebentar dan minum kopi. Maklum kopi siang belum sempat di teguk.\nMencari kedai kopi di Cebu City tak semudah yang dibayangkan. Nama-nama kedai kopi spesialti ternyata tak banyak. Maka kami mencari kedai kopi secara acak saja yang dekat dengan kami. Ditemukanlah kedai kopi bernama Coffee Stop.\nCoffee Stop ternyata agak sulit ditemukan. Kami berhenti sesuai titik kendaraan online tapi tak melihat tanda-tanda Coffee Stop berada. Di kebingungan itu kami menemukan tulisan “Coffee Stop” di sebuah dinding dengan arah panah. Oh ternyata kedai kopi ini berada di lantai dua. Tersembunyi di balik pintu putih. Pantas tak mudah ditemukan itu!\nNaik ke lantai dua ternyata Coffee Stop sudah diisi beberapa orang. Ada dua ruangan di lantai dua. Pertama yang dekat dengan coffee bar dan yang kedua membentuk sudut nyaman. Kedai kopi ini berdesain minimalis dengan warna dominan putih yang membuatnya terang dan nyaman. Mungkin juga agar terlihat luas.\nCoffee Stop ini hanya menggunakan mesin espresso one boiler kecil dan tidak menyediakan manual brew. Tak apalah yang penting kami bisa ngopi dan berjeda sejenak dari lelahnya mengeksplorasi Cebu City ini. Saya memesan secangkir caffe latte yang rasanya biasa saja dan teman saya memesan Iced Americano. Oh iya kami juga memesan fudgy brownie yang diberi nama Better Than Your Boyfriend hahaha.\nYang membuat betah tempat ini dingin dan nyaman. Dan meski diisi banyak mahasiswa yang sedang belajar kelompok atau mengerjakan tugas, tempat ini tetap terjaga kenyamanannya. Menurut saya Coffee Stop ini memang kedai kopinya mahasiswa karena lokasinya berada di dekat kampus.\n Meskipun Coffee Stop bukanlah kedai kopi spesialti seperti yang saya harapkan, tetapi setidaknya tempat ini berjasa menjaga kewarasan saya dari kekurangan kafein sore itu",
            imageUrl: "https://majalah.ottenstatic.com/uploads/2019/12/5-1.jpg",
            author: "Mustika Treisna Yuliandri",
            tag: "Cafe & Travel,International,Asia",
            createdAt: "10-12-2019"
        },
        {
            title: "MENCARI RASIO KOPI UNTUK SEDUHAN",
            content: "The golden ratio for brewing coffee, bukan hal sederhana tidak juga susah, perlu mencari rasio kopi yang tepat untuk seduhan, tested, test, and testing.\nUntuk menemukan formula tepat dalam menyajikan secangkir kopi yang nikmat perlu perhitungan. Rasio kopi dan air, coffee grind size, dan waktu seduhan saling berkaitan dalam satu jejaring yang sama. Rasio kopi dan air sudah tepat, jika grind size kopi ternyata tidak diperhatikan juga berdampak pada rasa kopi, dan lagi waktu seduhan juga tidak bisa dipandang sebelah mata. Mengaliri air juga perlu memastikan waktu yang sesuai untuk seduhan kopi.\nDalam hal ini, kesampingkan sejenak coffee grind size dan juga waktu seduhan. Ada apa dengan rasio kopi dan air, bagaimana menghitung berapa gram kopi yang tepat untuk menyajikan secangkir kopi berukuran 10 ml? Pernahkah kamu memikirkannya, bagaimana barista melakukan perhitungan rasio, antara kopi dan air untuk secangkir kopi di meja kamu hari ini.\nPerihal kopi, barista adalah teman berbual yang tepat. Mereka akan selalu jujur, mulai dari mana biji kopi itu berasal, sampai berakhir di secangkir meja kamu. Pastinya dengan senang hati, mereka-barista akan merasa menemukan teman masa kecil yang sama, menyukai apa pun tentang kopi. Mulailah dari obrolan ringan, sampai bahasan tentang rasio kopi dan air.\nCoffee to Water Ratio atau Water to Coffee Ratio\nPernahkah mendengar istilah 1: 12 atau 1: 16, ya benar, sebutan tersebut adalah rasio perbandingan kopi dan air.Namun, mana yang benar penyebutannya 1: 16 atau 16: 1 untuk menyatakan perbandingan rasio.\nRasio Air Seduhan; oz dan ml\nPerhitungan sederhananya, 1 oz = 30 ml. Jika cup yang menampung 7 oz berapa rasio kopi yang harus di-grind untuk secangkir kopi itu. Cobalah untuk mengkonversikan terlebih dahulu ke dari oz ke ml. Dengan rasio 1:18 maka 7oz = 210ml. Baiklah konversi ke ml sudah didapat 1g : 18ml maknanya ? : 210ml, bisa dihitung dengan 210ml/18ml = 12g. Maka 1g : 18ml sama artinya dengan 12g : 210ml.",
            imageUrl: "https://majalah.ottenstatic.com/uploads/2017/05/white_acaia.png",
            author: "Yoga A. Mustika",
            tag: "Tips",
            createdAt: "30-05-2017"
        }
    ]